name: book manager app infrasture deletion
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  security-group:
    runs-on: ubuntu-latest
    needs: [autoscaling, load-balancer]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform initialize
        run: cd module6/iac/terraform/instance-creation && terraform init
      
      - name: terraform plan for infrastructure
        run: cd module6/iac/terraform/instance-creation && terraform plan -destroy
      
      - name: terraform apply for infrastructure
        run: cd module6/iac/terraform/instance-creation && terraform apply -destroy -auto-approve
  
  load-balancer:
    runs-on: ubuntu-latest
    needs: [autoscaling]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform initialize
        run: cd module6/iac/terraform/load-balancer && terraform init
      
      - name: terraform plan for infrastructure
        run: cd module6/iac/terraform/load-balancer && terraform plan -destroy
      
      - name: terraform apply for infrastructure
        run: cd module6/iac/terraform/load-balancer && terraform apply -destroy -auto-approve

  autoscaling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform initialize
        run: cd module6/iac/terraform/autoscaling && terraform init
      
      - name: terraform plan for infrastructure
        run: cd module6/iac/terraform/autoscaling && terraform plan -destroy
      
      - name: terraform apply for infrastructure
        run: cd module6/iac/terraform/autoscaling && terraform apply -destroy -auto-approve
  

